[project]
name = "killteamcalculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Loïc Musy", email = "loic@famille-musy.com" }
]
requires-python = ">=3.13"
dependencies = []
